name: Flutter Build

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Set Environment Variables
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          API_SERVER: ${{ secrets.API_SERVER }}
        run: |
          echo "Firebase API Key: $FIREBASE_API_KEY"
          echo "Signing Key Password: $SIGNING_KEY_PASSWORD"
          echo "Rendezvous Server: $RENDEZVOUS_SERVER"
          echo "RS Public Key: $RS_PUB_KEY"
          echo "API Server: $API_SERVER"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Build Artifacts (if required)
        if: inputs.upload-artifact == true
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk